### PR TITLE
Fixed flow.sync() options bug and updated Esprima version to enable E…

### PR DESCRIPTION
**Pull request by Animadei**
…S6 enableTransform() support.

### CODE REVIEW

**Comment by scriby** [comment]
Thanks for submitting this! I'll take a closer look at it later, but wanted to give you one suggestion for dealing with the request library.

You can just do it like this:

```
var response = flow.sync(request(...), flow.add());
var body = response.body; //No need to deal with responseFormat, just grab the body from here

//Same thing if you are using transformation...
var rseponse = request(...).sync();
var body = response.body;
```

**Comment by Animadei** [comment]
Thank you for the suggestion. I have actually been doing what you suggested for the past year until learning how to use different ways of flow.sync() modes broke all my assumptions. Newer developers would not understand how your example works so for the benefit of everyone I'm writing out the explanation (not anything directed to you).

request() takes a callback function accepting 3 parameters (error, response, body):

```Javascript
request(link, function (error, response, body) {
  // error - Error object if something bad happens this is non-NULL
  // response - Is an HTTP response object
  // body - Is the content of the web page fetched
});
```

By default flow.add() generates a callback functions that assumes a 2 parameter prototype:

```Javascript
function callback (error, result) {
  // error - Any kind of error including Error object
  // result - One return value to return back to flow.wait() caller
  // Asyncblock actually uses the arguments variable to parse for the first two arguments
}
```

By default only 2 parameters (error, result) are stored, and only result is returned back to the flow.wait() caller, the return value of the flow.sync() is the content of the <i>response</i> variable of the request() call. The <i>body</i> of the request() call was thrown away.

The reason why Scriby's suggestion works is because of the assumption that the <i>response</i> variable returned by flow.sync() stores an HTTP response object where <i>response.body</i> is a data member. The <i>body</i> variable given to the callback of request() was ignored and thrown away.

If HTTP response object changes its implementation to no longer contain a data member called <i>body</i>, then the 3 parameters (error, param1, param2) is needed and the only way to retrieve param2 from the callback context called by request() is by using the responseFormat to retrieve it.

This example was particularly confusing at first because the identifier called <i>body</i> actually exists in multiple context so I never thought about that the body variable from the callback was different than the body variable returned by flow.sync(). This is the reason why I appended numbers to variable names of the callback parameters in my example to show we're actually working with different instances of the body variable.

**Comment by scriby** [comment]
Wow, I had totally forgotten about the flow.sync syntax in req3 through req5. I think I had intended to deprecate it in 2.0.0. Is that a syntax you use?

If so, would you mind adding tests to cover those usages? Otherwise, I'd prefer to just deprecate it and release a 3.0.0.

Thanks!

**Comment by Animadei** [comment]
Our engineers prefers syntax 3 to 5, especially 5. To them the return variables/types were obvious because it looks like a function prototype in C/C++. The flow.add() in the parameter makes the code harder to read and the return parameters harder to locate. We can help develop tests. Can you point me to what tests you need and how you like them done?

**Comment by scriby** [comment]
I pretty much always use transformation on my projects, so I don't deal with the other syntaxes very often.

For the tests, add them around here: https://github.com/scriby/asyncblock/blob/2db71965bb6d09b4f509b52b7031530b71db42bd/tests/functionality.js#L643

Just perform a call using all the syntaxes and verify the arguments get passed correctly.

Execute `./run_tests.sh`. Hopefully you are on linux or OSX since that isn't going to run on windows :(

**Comment by Animadei** [comment]
Reporting in. <i>vow</i> test vectors under <i>./tests/*</i> run fine under Cygwin and VS2015 under Windows 7. Vectors also ran fine under Arch Linux v4.1 and Cent OS 7.

My previous commit didn't pass all vectors. I've since uploaded a new fix in <i>flow.js</i> that passes all tests and added two new basic tests.

**Comment by scriby** [comment]
Thanks for your contribution!

**Comment by scriby** [comment]
Changes published under 2.2.0

**Pull request merged**
